name: Move new issues into Backlog

on:
  issues:
    types: [ opened ]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@6c406e8a244fdf6bbf79e6cc8a91504a48d2c2ce # v1.9.2
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/add-to-github-projects
      - uses: actions/add-to-project@1b844f0c5ac6446a402e0cb3693f9be5eca188c5 # v0.6.1
        with:
          project-url: https://github.com/orgs/2rabs/projects/2
          github-token: ${{ steps.app-token.outputs.token }}
