name: Move new issues into Backlog

on:
  issues:
    types: [ opened ]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # https://github.com/marketplace/actions/add-to-github-projects
      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7 # v1.0.0
        with:
          project-url: https://github.com/orgs/2rabs/projects/2
          github-token: ${{ steps.app-token.outputs.token }}
